
module.exports = {
	
 'button':[
  {	
   'type':'click',
   'name':'等待更新',
   'key':'V1001_TODAY_LATEST',
   'sub_button':[]
  },
  {
   'name':'嘻而时学',
   'sub_button':[
   {	
     'type':'click',
     'name':'时间管理',
     'key':'V1001_TYPE_KEHUAN',
     'sub_button':[]
   },
   {
     'type':'click',
     'name':'OKR',
     'key':'V1001_TYPE_XUANYI',
     'sub_button':[]
   },
   {
     'type':'click',
     'name':'读后感',
     'key':'V1001_TYPE_AIQING',
     'sub_button':[]
   }]
  },
  {
   'name':'一起玩耍',
   'sub_button':[
   {	
     'type':'click',
     'name':'电玩',
     'key':'V1001_AREA_DALU',
     'sub_button':[]
   },
   { 
     'type':'click',
     'name':'民俗',
     'key':'V1001_AREA_GANGTAI',
     'sub_button':[]
   },
   {
     'type':'click',
     'name':'历史',
     'key':'V1001_AREA_OUMEI',
     'sub_button':[]
   },
   {
     'type':'click',
     'name':'常识',
     'key':'V1001_AREA_HANGUO',
     'sub_button':[]
   }]
  }]
}